### ISSUE TITLE
Add Windows build

### ISSUE THREAD

**Issue by nileshtrivedi** [nileshtrivedi/devtoolbox#2]
This requires a Windows machine to build which I don't have at the moment.

**Comment by kurianbenoy-aot** [comment]
@nileshtrivedi how can I do a build in windows?

**Comment by adityathakurxd** [comment]
Hey @kurianbenoy-aot,
Maybe this might help you create the Windows build.
https://youtu.be/57LtKoMeOUM

**Comment by nileshtrivedi** [comment]
Please check the PR @Harishwarrior has been working on here: https://github.com/nileshtrivedi/devtoolbox/pull/7

**Comment by nileshtrivedi** [comment]
Fixed with #7. Closing.
